### ISSUE TITLE
host first vs task first task chaining

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#844]
Currently rex only supports task first task chaining.  I want to add host first task chaining.  A goal of this issue is to explain what this change will look like to the user.   The other goal of this issue is to create a detailed plan to get there so I can make the changes in small incremental prs instead of one gigantic pr.

# User interface

**Command line options**
Users will use the `-eo` option to indicate which execution order they prefer.  The default value will be 'task-first' for backwards compatibility.  Next major version bump should probably flip that because host-first execution is faster:
```
rex -eo host-first -G production deploy:product1
rex -eo task-first -G production deploy:product1
```

**Rexfile dsl changes**
Users will also be able to specify a default execution order in their Rexfile:
```
execution_order 'host-first';
```

**Task execution summary**
Users will also see a summary of success/failure at the end of a rex run.  The summary of failures will be sorted by host first when using host first execution.  And it will be sorted by task first when using task first execution.  

# How to get there
  - [ ] REFACTOR - Move all logic in `Rex::TaskList->run()` and `Rex::RunList->new->run_tasks()`into `Rex::TaskList::Base->run()` and `Rex::TaskList::Parallel_ForkManager->run()`.  Move all logic in `run()` methods into `run_task()`.
  - [ ] REFACTOR - Move all logic for creating `$forked_sub` in `Rex::TaskList::Base->run_task()` and `Rex::TaskList::Parallel_ForkManager->run_task()` out of `run_task()` and into `build_child_coderef()`.
  - [ ] REFACTOR - Move @SUMMARY logic and shared variables from `Rex::Fork::Task` and `Rex::Fork::Manager` into `Rex::TaskList::Base->build_child_coderef()`.
  - [ ] REFACTOR - Move @SUMMARY logic and shared variables into `Rex::TaskList::Parallel_ForkManager->build_child_coderef()`.
  - [ ] `Rex::TaskList::Parallel_Forkanager->run()` will call 'run_host_first()` or `run_task_first()`.
  - [ ] Add `execution_order` to Rexfile dsl
  - [ ] Add `-eo` command line option
